### ISSUE TITLE
Cli.Parse not working on Mono 5

### ISSUE THREAD

**Issue by JorritPosthuma** [Nick-Lucas/EntryPoint#48]
`Cli.Execute` works fine, but `Cli.Parse` throws the following error. Works on Mono 4.8 though...

![screen shot 2017-05-24 at 13 15 33](https://cloud.githubusercontent.com/assets/412253/26400829/343aee3c-4083-11e7-9fca-3889a3583717.png)

**Comment by Nick-Lucas** [comment]
Hi @JorritPosthuma I'll have a look into this, thanks for the report.

I haven't actively tested EntryPoint on Mono, but would like to get it stable if you're planning on using the two together. Any reports you have would be very welcome.

**Comment by Nick-Lucas** [comment]
Notes:

* The code is failing on EntryPoint's `.GetHelp` extension, which tries to get a `HelpAttribute` on each define option.
* Mono [should return null](https://github.com/mono/mono/blob/master/mcs/class/referencesource/mscorlib/system/attribute.cs#L637) if the attribute has not been applied, but this doesn't seem to be happening.
* Instead Mono seems to be 'finding' 2 or more attributes 'matching' the `HelpAttribute` type, and [throwing](https://github.com/mono/mono/blob/master/mcs/class/referencesource/mscorlib/system/attribute.cs#L647)

@JorritPosthuma could you try a couple of things?

1. Try removing `Required` from each of your properties, just to get the number of attributes under 2. Do you get the same error?
2. Try applying a `[Help(detail)` attribute to each property. Do you still get an error?

I'm a little at a loss as to why Mono is doing this. Could you also check that you're on the latest 5.0 version? (5.0.1)

**Comment by JorritPosthuma** [comment]
Hi! Thanks for helping ☺️.

I tried 1 and 2, but it makes no difference. Even without any arguments, it's throwing the `AmbiguousMatchException`. I test it with Mono 5.0.1.1

**Comment by Nick-Lucas** [comment]
@JorritPosthuma I think I've fixed this and have put out 1.2.2 for you.

Let me know how it goes!

**Comment by JorritPosthuma** [comment]
Yes! It works! Thanks a lot!!!

**Comment by Nick-Lucas** [comment]
Great! Please don't hesitate to report any niggles you come up with. I rarely work with Mono, so EntryPoint least battle-hardened, there.

Closed by 6f59c1769cb80c897757b8a3b7b3b76ee0514f44

**Comment by JorritPosthuma** [comment]
Will do ☺️
