### ISSUE TITLE
Option attribute is only for properties

### ISSUE THREAD

**Issue by pouladpld** [Nick-Lucas/EntryPoint#50]
Attributes could be available for fields as well. I don't see any need to generate more code by declaring unnecessary properties.

<https://github.com/Nick-Lucas/EntryPoint/blob/705758b737ae435066214bc047ceefea62c9daed/src/EntryPoint/OptionAttribute.cs#L15>

**Comment by Nick-Lucas** [comment]
Hi @pouladpld,

Thanks for the suggestion. I am open to any ideas, but for this I'd need a real justification for the change. 

It's not quite as simple as changing the attribute, the whole tool actually looks at properties, using reflection. I originally felt that the simplicity of just supporting properties would be better for maintainability, while giving a lot of power to the user, and giving you 'field-like' simplicity using auto-props. Additionally reflection is known to be slower than hard-coding mapping against known models, and so checking fields would effectively double the processing EntryPoint is required to handle.

I'm assuming you know autoprops, but for the sake of documentation, the following is already pretty simple and terse:
```C#
// What we can do now:
[Option(...)]
public bool SomeOpt { get; set; }

// What we can't do right now
[Option(...)]
public bool SomeOpt;
```

Let me know if you have any further arguments for this, as I'll be happy to weight up anything against the following:
* Performance
* Adequate terseness with auto-props
* Flexibility of implementation (getters, setters, and access control) with props
