### ISSUE TITLE
All "\" characters are removed from string parameters

### ISSUE THREAD

**Issue by pouladpld** [Nick-Lucas/EntryPoint#51]
Passing such valid argument on command line 
```bash
program.exe command --path "C:\path\to\dir"
```

will result in getting the following from args!

```c#
bool trueValue = args.Path == "C:pathtodir";
```

**Comment by Nick-Lucas** [comment]
Yes, this is a limitation of terminals in general and not EntryPoint.
\ is the escape character. If you want to use it you must escape it `\\` or change your backslashes for forward (`/`) slashes. You will find this behaviour the same across all command line applications.

**Comment by pouladpld** [comment]
Have you tried this?

```bash
dotnet run -- --path "C:\dir"
```

**Comment by Nick-Lucas** [comment]
Last time I looked into this (it was reported once before) the outcome was my above comment. The shell processes commands before they're passed to the application, and depending on your shell, escapes will (or will not) be stripped.

It is interesting that I can reproduce `\` working fine in the dotnet CLI under bash, which implies there may be a CLR setting I'm not aware of, but in my experience the behaviour you've described is how CLI applications work.

I will have more of a think on this, but if you can propose a solution that would be very helpful. The arguments which .NET apps are given access to have already been processed by the shell, so I didn't think it was possible to work around this. Luckily the code is open-source: https://github.com/dotnet/cli/blob/d55ed34d2ed91c287d1c5599768d834651307c68/src/dotnet/Program.cs

**Comment by Nick-Lucas** [comment]
Okay there is likely something unexpected going on here. Thanks for the report.

Reproduction:
```C#
    class Program {
        static void Main(string[] args) {
            Console.WriteLine(args[1]);
            var a = Cli.Parse<CliArgs>(args);
            Console.WriteLine(a.Path);
        }
    }

    class CliArgs : BaseCliArguments {
        public CliArgs() : base("args") {
        
        }

        [OptionParameter("path", 'p')]
        public string Path { get; set; }
    }
```

Output:
```bash
dotnet run --path "hel\lo"
hel\lo
hello
```

So it appears the parsing is doing something it shouldn't. I will do some investigation. Thanks for the report and sorry for initially misunderstanding @pouladpld

**Comment by pouladpld** [comment]
Fix should be fairly easy. I really want to make a PR for it but my schedule is pretty tight these days.

**Comment by Nick-Lucas** [comment]
It's no problem, I will take a look tonight, and expect it's a very simple tweak.

**Comment by Nick-Lucas** [comment]
@pouladpld if you like, have a look here: https://github.com/Nick-Lucas/EntryPoint/pull/52

I believe this fixes the issue, it was a side effect of a design choice, which has now been removed.

**Comment by Nick-Lucas** [comment]
1.2.3 Deployed

Let me know if you come across any other oddities
