### ISSUE TITLE
BaseOptionAttribute LongName and ShortName

### ISSUE THREAD

**Issue by TheColonel2688** [Nick-Lucas/EntryPoint#54]
Can the Accessibility Level on `ShortName` and `LongName` in `BaseOptionAttribute` be changed to `public`? or at least `public` get?

I would like to use those attributes in my code.

**Comment by Nick-Lucas** [comment]
Hi @TheColonel2688 

I don't see any reason they couldn't be public get, private set, but I'd definitely question the use case?

Is there some functionality that EntryPoint isn't providing, which you feel you need to implement in your app? If it's really unique to you then go ahead and open a pull request :)

Full disclosure: I'm not _actively_ maintaining EntryPoint right now, as I'm not using it on any current projects, though I'm content it's been stable and production ready for a long time. I'm happy to offer support and might even be able to maintain it again in the next few months.

**Comment by TheColonel2688** [comment]
Basically, I just need to get the LongName as a string. I am having my app register itself as a service, so I need to pass the actual option flag string for my run-as-service flag to windows so that when it calls my app and runs in service mode.

yes, I could just give it a string literal but I figured it would be cleaner to get it for the OptionsAttribute so that if I change it in the CLIArguemtn definitions class it will auto-update.

**Comment by Nick-Lucas** [comment]
Thanks for the PR. I've merged it and will try to get out 1.3.0 shortly. Hopefully all the CI nuts and bolts still work after a couple years away!

**Comment by Nick-Lucas** [comment]
Okay that's deployed: https://www.nuget.org/packages/EntryPoint/

**Comment by TheColonel2688** [comment]
Sweet thank you sir.
